name: "Publish Web Build to GitHub Pages"
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  export-web:
    runs-on: ubuntu-latest
    name: Export Web Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot and Templates
        run: |
          python3 scripts/setup_godot.py

      - name: Export Project to Web
        run: |
          mkdir -p build/Web
          ./Godot_v4.6.3-stable_linux.x86_64 --verbose --headless --path . --export-release "Web" build/Web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/Web
          force_orphan: true
